<?xml version="1.0" encoding="utf-8"?>
<project xmlns="http://www.axway.com/mappingServices/project" createdBy="Sonedi" lastModifiedBy="Sonedi" flowName="/Sinacofi_EC1/Mapping Flows/project.dmlflw" checksumTest="true" creationDate="22/05/2024 09:11:24 -0400" engineType="DML" lastModifiedDate="31/05/2024 11:50:38 -0400" engineVersion="2.1">
   <deploymentInformation>
      <deployment name="Sinacofi_EC1_EC1_FT3" id="81512903-9143-433c-9b8c-23a69e6774dc" port="6443" date="31/05/2024 11:50:38 -0400" user="Sonedi (rcarrasco)" projectType="DML-2.1" version="1" from="DESKTOP-FSE9076" host="100.66.54.10">
         <content>
            <mapping>Mapping Flows/EC1_FT3.dmlflw</mapping>
         </content>
      </deployment>
   </deploymentInformation>
</project>