<?xml version="1.0" encoding="utf-8"?>
<project xmlns="http://www.axway.com/mappingServices/project" createdBy="N" lastModifiedBy="olive" flowName="/Sinacofi_P39/Mapping Flows/project.dmlflw" checksumTest="true" creationDate="09/02/2024 17:55:42 -0300" engineType="DML" lastModifiedDate="15/05/2024 11:53:38 -0400" engineVersion="2.1">
   <deploymentInformation>
      <deployment name="Sinacofi_P39_P39_FT3" id="d411b306-e229-4118-a42d-c709ee489e56" port="6443" date="15/05/2024 11:53:38 -0400" user="olive (osilva)" projectType="DML-2.1" version="1" from="DESKTOP-OIQD116" host="100.66.54.10">
         <content>
            <mapping>Mapping Flows/P39_FT3.dmlflw</mapping>
         </content>
      </deployment>
   </deploymentInformation>
</project>