<?xml version="1.0" encoding="utf-8"?>
<project xmlns="http://www.axway.com/mappingServices/project" createdBy="N" lastModifiedBy="olive" flowName="/Sinacofi_E01/Mapping Flows/project.dmlflw" checksumTest="true" creationDate="09/02/2024 17:55:42 -0300" engineType="DML" lastModifiedDate="14/05/2024 15:30:47 -0400" engineVersion="2.1">
   <deploymentInformation>
      <deployment name="Sinacofi_E01_E01_FT3" id="79f510b0-8ffa-40ba-ba5c-195043e58d22" port="6443" date="14/05/2024 15:30:47 -0400" user="olive (osilva)" projectType="DML-2.1" version="1" from="DESKTOP-OIQD116" host="100.66.54.10">
         <content>
            <mapping>Mapping Flows/E01_FT3.dmlflw</mapping>
         </content>
      </deployment>
   </deploymentInformation>
</project>