<?xml version="1.0" encoding="utf-8"?>
<project xmlns="http://www.axway.com/mappingServices/project" createdBy="Sonedi" lastModifiedBy="Sonedi" flowName="/Sinacofi_EF1/Mapping Flows/project.dmlflw" checksumTest="true" creationDate="22/05/2024 09:11:50 -0400" engineType="DML" lastModifiedDate="31/05/2024 12:30:43 -0400" engineVersion="2.1">
   <deploymentInformation>
      <deployment name="Sinacofi_EF1_EF1_FT3" id="eb256686-0b8f-4747-af65-83375849eed6" port="6443" date="31/05/2024 12:30:43 -0400" user="Sonedi (rcarrasco)" projectType="DML-2.1" version="1" from="DESKTOP-FSE9076" host="100.66.54.10">
         <content>
            <mapping>Mapping Flows/EF1_FT3.dmlflw</mapping>
         </content>
      </deployment>
   </deploymentInformation>
</project>