<?xml version="1.0" encoding="utf-8"?>
<project xmlns="http://www.axway.com/mappingServices/project" createdBy="Sonedi" lastModifiedBy="olive" flowName="/Sinacofi_I12/Mapping Flows/project.dmlflw" checksumTest="true" creationDate="06/02/2024 15:50:38 -0300" engineType="DML" lastModifiedDate="29/05/2024 17:17:21 -0400" engineVersion="2.1">
   <deploymentInformation>
      <deployment name="Sinacofi_I12_I12_FT3" id="0a84307d-94fe-4ff7-9f66-a1da5e6810e2" port="6443" date="29/05/2024 17:17:21 -0400" user="olive (osilva)" projectType="DML-2.1" version="1" from="DESKTOP-OIQD116" host="100.66.54.10">
         <content>
            <mapping>Mapping Flows/I12_FT3.dmlflw</mapping>
         </content>
      </deployment>
   </deploymentInformation>
</project>