<?xml version="1.0" encoding="utf-8"?>
<project xmlns="http://www.axway.com/mappingServices/project" createdBy="paulo" lastModifiedBy="gerii" flowName="/Sinacofi_ER1/Mapping Flows/project.dmlflw" checksumTest="true" creationDate="09/02/2024 10:54:32 -0300" engineType="DML" lastModifiedDate="31/05/2024 15:17:35 -0400" engineVersion="2.1">
   <deploymentInformation>
      <deployment name="Sinacofi_ER1_ER1_FT3" id="a8788b8d-3220-4ecc-849a-9fd057e5c114" port="6443" date="31/05/2024 15:17:35 -0400" user="gerii (aaravena)" projectType="DML-2.1" version="1" from="DESKTOP-46NE65B" host="100.66.54.10">
         <content>
            <mapping>Mapping Flows/ER1_FT3.dmlflw</mapping>
         </content>
      </deployment>
   </deploymentInformation>
</project>