<?xml version="1.0" encoding="utf-8"?>
<project xmlns="http://www.axway.com/mappingServices/project" createdBy="Sonedi" lastModifiedBy="gerii" flowName="/Sinacofi_P15/Mapping Flows/project.dmlflw" checksumTest="true" creationDate="06/02/2024 15:50:38 -0300" engineType="DML" lastModifiedDate="02/07/2024 17:45:14 -0400" engineVersion="2.1">
   <deploymentInformation>
      <deployment name="Sinacofi_P15_P15_FT3" id="e17cd692-d6d5-4aaf-9914-6f081b5416ee" port="6443" date="02/07/2024 17:45:14 -0400" user="gerii (aaravena)" projectType="DML-2.1" version="4" from="DESKTOP-46NE65B" host="100.66.54.10">
         <content>
            <mapping>Mapping Flows/P15_FT3.dmlflw</mapping>
         </content>
      </deployment>
   </deploymentInformation>
</project>