<?xml version="1.0" encoding="utf-8"?>
<project xmlns="http://www.axway.com/mappingServices/project" createdBy="paulo" lastModifiedBy="gerii" flowName="/Sinacofi_C77/Mapping Flows/project.dmlflw" checksumTest="true" creationDate="09/02/2024 10:54:32 -0300" engineType="DML" lastModifiedDate="30/05/2024 16:53:02 -0400" engineVersion="2.1">
   <deploymentInformation>
      <deployment name="Sinacofi_C77_C77_FT3" id="559aa708-0bf8-4a9c-b37a-7d1fb607aa44" port="6443" date="30/05/2024 16:53:02 -0400" user="gerii (aaravena)" projectType="DML-2.1" version="1" from="DESKTOP-46NE65B" host="100.66.54.10">
         <content>
            <mapping>Mapping Flows/C77_FT3.dmlflw</mapping>
         </content>
      </deployment>
   </deploymentInformation>
</project>